name: Deploy Antora Documentation to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java (required for Antora)
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'  

      - name: Install Antora
        run: |
          curl -sL https://dl.antora.org/antora-3.1.9.tar.gz | tar xz
          sudo mv antora-3.1.9/bin/antora /usr/local/bin

      - name: Build the documentation site
        run: antora antora.yml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: main
